blueprint:
  name: Leak detection & notifier
  description: Send a notification when any configured moisture sensor becomes moist, as well as trigger an audio device to play a notificiton
  domain: automation
  input:
    notify_device:
      name: Notify device
      description: "The device where the notification should be sent to."
      selector:
        entity:
          domain: mobile_app
          multiple: true

trigger:
  - event_data: {}
    event_type: state_changed
    platform: event

condition:
  - condition: template
    value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture" }}'
  - condition: template
    value_template: '{{ trigger.event.data.new_state.state == "on" }}'

action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  message: "{{ trigger.event.data.new_state.attributes.friendly_name }} has detected a leak."
  title: "Leak detected!"

mode: single